### PR TITLE
ADR: JSX files extension

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Review by mboperator — APPROVED** [review]

**Comment by mboperator** [comment]
This also helps developers identify which hyphen-separated file contains react components

**Review by dancingshell — APPROVED** [review]
I've been torn before on whether files with custom hooks should get `jsx` (or `tsx`) extension vs `js`. Technically they aren't returning jsx but they do often use react and sometime I end up adding context/provider and end up having to change the extension later. Any thoughts?

**Comment by yordis** [comment]
@dancingshell only JSX syntax, that means you could use other React/Preact/X framework, without having to change the extension if the file does not contain JSX syntax in it.

**Comment by yordis** [comment]
Moved to Reviewing state

**Pull request merged**
